/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-west-2",
  aws_appsync_graphqlEndpoint: "http://172.16.3.175:20002/graphql", // Thanks to api mock, you can use graphql in local env
  aws_appsync_region: "us-west-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-fakeApiId123456",
  aws_appsync_dangerously_connect_to_http_endpoint_for_testing: true,
  aws_cognito_identity_pool_id:
    "us-west-2:3ccbc40b-c015-4c68-8213-84be73c0a352",
  aws_cognito_region: "us-west-2",
  aws_user_pools_id: "us-west-2_J6ssJJg7l",
  aws_user_pools_web_client_id: "4sh4f7n1j7r8c2rdaripajequv",
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
